"""Derive deterministic tree nodes from canonical span heading_path values.

For each unique heading_path in the spans, a hierarchy of tree nodes is
produced by splitting on the " > " separator.  Node IDs are deterministic
(uuid5) so that the same version + heading always yields the same node_id.

summary_text is generated by:
- Leaf nodes: concatenating raw_text from all covered spans
- Parent nodes: aggregating summary_text from all child nodes

Semantic grouping seam: spans with same heading_path but clearly divergent
semantic content are split into separate leaf groups with cluster_id markers.
"""

from __future__ import annotations

import uuid
from collections import defaultdict
from typing import Any
import unicodedata

MAX_SUMMARY_LENGTH = 1000


def _detect_semantic_cluster(texts: list[str]) -> list[int]:
    """Minimal semantic clustering: detect divergent content domains.

    Simple heuristic approach using keyword detection for common divergent domains.
    Returns cluster indices (0, 1, 2, ...) for each text.

    This is a minimal seam implementation - not a full clustering framework.
    """
    # Domain keyword signatures for semantic divergence detection
    domain_keywords = {
        "ml": [
            "machine learning",
            "neural network",
            "deep learning",
            "algorithm",
            "model",
            "training",
        ],
        "cooking": [
            "cooking",
            "recipe",
            "pasta",
            "ingredient",
            "dish",
            "food",
            "kitchen",
        ],
        "medicine": ["medical", "health", "doctor", "patient", "treatment", "disease"],
        "finance": ["finance", "investment", "stock", "market", "money", "bank"],
        "sports": ["sports", "game", "team", "player", "match", "score"],
    }

    clusters: list[int] = []
    cluster_map: dict[str, int] = {}

    for text in texts:
        text_lower = text.lower()
        detected_domain = None

        # Check which domain this text belongs to
        for domain, keywords in domain_keywords.items():
            if any(kw in text_lower for kw in keywords):
                detected_domain = domain
                break

        # Assign cluster based on domain
        if detected_domain:
            if detected_domain not in cluster_map:
                cluster_map[detected_domain] = len(cluster_map)
            clusters.append(cluster_map[detected_domain])
        else:
            # Default cluster groups all unclassified content together while
            # remaining distinct from any named semantic domain clusters.
            clusters.append(cluster_map.setdefault("default", len(cluster_map)))

    return clusters


def _tree_span_sort_key(span: dict[str, Any]) -> tuple[str, int, str, str]:
    """Return a total order that is stable across equivalent input shuffles."""
    semantic_domain = span.get("semantic_domain", "")
    normalized_domain = (
        " ".join(unicodedata.normalize("NFKC", semantic_domain).split()).casefold()
        if type(semantic_domain) is str
        else ""
    )
    offset = span.get("start_offset", span.get("offset", 0))
    stable_offset = offset if type(offset) is int else 0
    return (
        normalized_domain,
        stable_offset,
        str(span.get("span_id", "")),
        str(span.get("raw_text", "")),
    )


class TreeGenerator:
    def _summarize_leaf_spans(self, grouped_spans: list[dict[str, Any]]) -> str | None:
        """Concatenate raw_text from spans, truncated to 1000 chars.

        Returns None if no spans carry raw_text.
        """
        span_texts = [s.get("raw_text", "") for s in grouped_spans if s.get("raw_text")]
        raw_summary = " ".join(span_texts) if span_texts else None
        if raw_summary and len(raw_summary) > MAX_SUMMARY_LENGTH:
            return raw_summary[:MAX_SUMMARY_LENGTH]
        return raw_summary

    def _build_node(
        self,
        *,
        node_id: uuid.UUID,
        version_id: uuid.UUID,
        parent_id: uuid.UUID | None,
        level_no: int,
        title: str,
        heading_path: str,
        grouped_spans: list[dict[str, Any]],
        is_leaf: bool,
        cluster_id: int | None = None,
    ) -> dict[str, Any]:
        page_numbers = [
            page_no
            for span in grouped_spans
            if isinstance(page_no := span.get("page_no"), int)
        ]
        node_dict = {
            "node_id": node_id,
            "version_id": version_id,
            "parent_node_id": parent_id,
            "node_type": "chapter" if level_no == 0 else "section",
            "level_no": level_no,
            "title": title,
            "heading_path": heading_path,
            "page_start": min(page_numbers) if page_numbers else None,
            "page_end": max(page_numbers) if page_numbers else None,
            "summary_text": self._summarize_leaf_spans(grouped_spans)
            if is_leaf
            else None,
        }
        # Add cluster_id only for leaf nodes with semantic grouping
        if is_leaf and cluster_id is not None:
            node_dict["cluster_id"] = cluster_id
        return node_dict

    def _group_spans_by_heading_path(
        self, spans: list[dict[str, Any]]
    ) -> dict[tuple[str, ...], list[dict[str, Any]]]:
        paths: dict[tuple[str, ...], list[dict[str, Any]]] = defaultdict(list)
        for span in sorted(spans, key=_tree_span_sort_key):
            heading_path = span.get("heading_path") or "(root)"
            parts = [p.strip() for p in heading_path.split(" > ") if p.strip()]
            if not parts:
                parts = ["(root)"]
            paths[tuple(parts)].append(span)
        return paths

    def _build_parent_nodes(
        self,
        *,
        parts: tuple[str, ...],
        grouped_spans: list[dict[str, Any]],
        version_id: uuid.UUID,
        nodes: list[dict[str, Any]],
        key_to_id: dict[tuple[Any, ...], uuid.UUID],
    ) -> uuid.UUID | None:
        parent_id: uuid.UUID | None = None
        for idx, part in enumerate(parts[:-1]):
            key = (" > ".join(parts[: idx + 1]), idx)
            if key not in key_to_id:
                node_id = uuid.uuid5(
                    uuid.NAMESPACE_URL,
                    f"{version_id}:{key[0]}:{idx}",
                )
                key_to_id[key] = node_id
                nodes.append(
                    self._build_node(
                        node_id=node_id,
                        version_id=version_id,
                        parent_id=parent_id,
                        level_no=idx,
                        title=part,
                        heading_path=key[0],
                        grouped_spans=grouped_spans,
                        is_leaf=False,
                    )
                )
            parent_id = key_to_id[key]
        return parent_id

    def _append_leaf_nodes(
        self,
        *,
        parts: tuple[str, ...],
        grouped_spans: list[dict[str, Any]],
        version_id: uuid.UUID,
        parent_id: uuid.UUID | None,
        nodes: list[dict[str, Any]],
        node_spans: list[dict[str, Any]],
        key_to_id: dict[tuple[Any, ...], uuid.UUID],
    ) -> None:
        leaf_level = len(parts) - 1
        leaf_title = parts[-1]
        base_heading_path = " > ".join(parts)

        cluster_to_spans = self._group_spans_by_semantic_cluster(grouped_spans)
        has_semantic_split = len(cluster_to_spans) > 1
        for cluster_idx, cluster_spans in sorted(cluster_to_spans.items()):
            leaf_id = self._get_or_create_leaf_node(
                base_heading_path=base_heading_path,
                leaf_level=leaf_level,
                leaf_title=leaf_title,
                cluster_idx=cluster_idx,
                cluster_spans=cluster_spans,
                version_id=version_id,
                parent_id=parent_id,
                has_semantic_split=has_semantic_split,
                nodes=nodes,
                key_to_id=key_to_id,
            )

            for ordinal, span in enumerate(cluster_spans):
                node_spans.append(
                    {
                        "node_id": leaf_id,
                        "span_id": span["span_id"],
                        "ordinal_no": ordinal,
                    }
                )

    def _group_spans_by_semantic_cluster(
        self, grouped_spans: list[dict[str, Any]]
    ) -> dict[int, list[dict[str, Any]]]:
        span_texts = [s.get("raw_text", "") for s in grouped_spans]
        cluster_indices = _detect_semantic_cluster(span_texts)
        cluster_to_spans: dict[int, list[dict[str, Any]]] = defaultdict(list)
        for span, cluster_idx in zip(grouped_spans, cluster_indices):
            cluster_to_spans[cluster_idx].append(span)
        return cluster_to_spans

    def _get_or_create_leaf_node(
        self,
        *,
        base_heading_path: str,
        leaf_level: int,
        leaf_title: str,
        cluster_idx: int,
        cluster_spans: list[dict[str, Any]],
        version_id: uuid.UUID,
        parent_id: uuid.UUID | None,
        has_semantic_split: bool,
        nodes: list[dict[str, Any]],
        key_to_id: dict[tuple[Any, ...], uuid.UUID],
    ) -> uuid.UUID:
        leaf_key: tuple[str, int] | tuple[str, int, int]
        if has_semantic_split:
            leaf_key = (base_heading_path, leaf_level, cluster_idx)
            node_seed = (
                f"{version_id}:{base_heading_path}:{leaf_level}:cluster{cluster_idx}"
            )
            cluster_id = cluster_idx
        else:
            leaf_key = (base_heading_path, leaf_level)
            node_seed = f"{version_id}:{base_heading_path}:{leaf_level}"
            cluster_id = None

        if leaf_key not in key_to_id:
            node_id = uuid.uuid5(uuid.NAMESPACE_URL, node_seed)
            key_to_id[leaf_key] = node_id
            nodes.append(
                self._build_node(
                    node_id=node_id,
                    version_id=version_id,
                    parent_id=parent_id,
                    level_no=leaf_level,
                    title=leaf_title,
                    heading_path=base_heading_path,
                    grouped_spans=cluster_spans,
                    is_leaf=True,
                    cluster_id=cluster_id,
                )
            )
        return key_to_id[leaf_key]

    def generate_tree(
        self,
        spans: list[dict[str, Any]],
        *,
        version_id: uuid.UUID,
    ) -> dict[str, list[dict[str, Any]]]:
        """Generate tree nodes and node-span links from canonical spans.

        Parameters
        ----------
        spans : list of dict
            Each dict must have keys: span_id, heading_path (str | None),
            page_no (int | None), raw_text (str).
        version_id : UUID
            The document version these spans belong to.

        Returns
        -------
        dict with keys "nodes" and "node_spans".
        """
        if not spans:
            return {"nodes": [], "node_spans": []}

        nodes: list[dict[str, Any]] = []
        node_spans: list[dict[str, Any]] = []
        key_to_id: dict[tuple[Any, ...], uuid.UUID] = {}
        paths = self._group_spans_by_heading_path(spans)

        for parts, grouped_spans in sorted(paths.items()):
            parent_id = self._build_parent_nodes(
                parts=parts,
                grouped_spans=grouped_spans,
                version_id=version_id,
                nodes=nodes,
                key_to_id=key_to_id,
            )
            self._append_leaf_nodes(
                parts=parts,
                grouped_spans=grouped_spans,
                version_id=version_id,
                parent_id=parent_id,
                nodes=nodes,
                node_spans=node_spans,
                key_to_id=key_to_id,
            )

        # Propagate summaries from children to parents
        nodes = self._propagate_summaries(nodes)

        return {"nodes": nodes, "node_spans": node_spans}

    def _propagate_summaries(self, nodes: list[dict[str, Any]]) -> list[dict[str, Any]]:
        """Propagate summary_text upward from child nodes to parent nodes.

        Parent nodes aggregate summaries from all their children.
        Returns a new list of node dictionaries instead of mutating in place.
        """
        nodes_by_id = {node["node_id"]: dict(node) for node in nodes}
        parent_to_children: dict[uuid.UUID | None, list[dict[str, Any]]] = defaultdict(
            list
        )
        for node in nodes_by_id.values():
            parent_to_children[node["parent_node_id"]].append(node)

        ordered_nodes = sorted(
            nodes_by_id.values(), key=lambda n: n["level_no"], reverse=True
        )
        for node in ordered_nodes:
            children = parent_to_children.get(node["node_id"], [])
            if not children or node["summary_text"] is not None:
                continue
            child_summaries = [
                nodes_by_id[child["node_id"]]["summary_text"]
                for child in children
                if nodes_by_id[child["node_id"]]["summary_text"] is not None
            ]
            if not child_summaries:
                continue
            raw_summary = " ".join(child_summaries)
            nodes_by_id[node["node_id"]] = {
                **node,
                "summary_text": raw_summary[:MAX_SUMMARY_LENGTH]
                if len(raw_summary) > MAX_SUMMARY_LENGTH
                else raw_summary,
            }

        return [nodes_by_id[node["node_id"]] for node in nodes]

    # Alias for backward compatibility with test naming
    generate = generate_tree
